name: stpo-processing
services:
- environment_slug: python
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: andipalmur/stpo-processing
  name: stpo-processing