name: stpo-processing
services:
  dockerfile_path: Dockerfile
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: andipalmur/stpo-processing
  name: stpo-processing